config/routes.rb
Rails.application.routes.draw do
  resources :mail_sends
  post 'mail_sends/confirm' => 'mail_sends#confirm'

  root 'mail_sends#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mail_sends_controller.rb
class MailSendsController < ApplicationController
  def index
    @sent_mails = []
    @queued_mails = []
  end

  def new
  end

  def confirm
    @subject = params[:Subject]
    @to = params[:To]
    @body = params[:Body]
  end

  def create
    send_email(subject: params[:Subject], to: params[:To], body: params[:Body])
  end

  private

  def send_email(subject:, to:, body:)
    secrets = Rails.application.secrets.select { |key, _value| key.to_s.include?('aws') }
    ses = Mail::SesClient.new(
      access_key_id: secrets[:aws_access_key_id],
      secret_access_key: secrets[:aws_secret_access_key]
    )
    ses.send(subject: subject, to: to, body: body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mail_sends_helper.rb
module MailSendsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsAwsSes
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/mail_sends/confirm.html.slim
.container
  h1 Confirm Sending Mail

  = form_tag(mail_sends_path) do
    .form-group
      = label_tag 'Subject'
      = text_field_tag 'Subject', @subject, class: 'form-control', readonly: true
    .form-group
      = label_tag 'To'
      = text_field_tag 'To', @to, class: 'form-control', readonly: true
    .form-group
      = label_tag 'Body'
      = text_area_tag 'Body', @body, class: 'form-control', rows: 10, readonly: true
    .form-group
      = button_tag 'submit', class: 'btn btn-primary btn-lg'
    .form-group
      = link_to('back', new_mail_send_path, class: 'btn btn-default')

app/views/mail_sends/create.html.slim
.container
  h1 Mail has been sent

  = link_to('Home', mail_sends_path, class: 'btn btn-default')

app/views/mail_sends/index.html.slim
h1 Hello

h1 Mail Sent History
- @sent_mails.each do |m|

h1 Pending Send Mails
- @queued_mails.each do |q|

= link_to('Create an Email', new_mail_send_path)

app/views/mail_sends/new.html.slim
.container
  h1 Create Sending Mail

  = form_tag(mail_sends_confirm_path) do
    .form-group
      = label_tag 'Subject'
      = text_field_tag 'Subject', '', class: 'form-control', placeholder: 'subject'
    .form-group
      = label_tag 'To'
      = text_field_tag 'To', '', class: 'form-control', placeholder: 'example@example.com'
    .form-group
      = label_tag 'Body'
      = text_area_tag 'Body', '', class: 'form-control', rows: 10, placeholder: 'Message body'
    .form-group
      = button_tag 'submit', class: 'btn btn-primary btn-lg'
    .form-group
      = link_to('back', mail_sends_path, class: 'btn btn-default')

app/views/mail_sends/show.html.slim
h1 Hello